version: "3"
services:
    redis:
        image: redis:7.0-alpine
        ports:
            - "6379:6379"

    db:
        image: postgres:14.2-alpine
        container_name: blog-app-db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        command: "postgres -c 'max_connections=500'"
        environment:
            - POSTGRES_DB=blog_app_development
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=260198
        ports:
            - "5432:5432"
    blog-app:
        build: .
        command: "./bin/dev"
        environment:
            - RAILS_ENV=development
            - POSTGRES_HOST=db
            - POSTGRES_DB=blog_app_development
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=260198
            - RAILS_MASTER_KEY=067e1610b0238d5388625a2cc1c1b679
        volumes:
            - app-storage:/rails/storage
        depends_on:
            - db
        ports:
            - "3000:3000"

volumes:
    postgres_data: {}
    app-storage: {}
